name: Delete merged branches (except dev)

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Delete branch except dev
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}
          # Branch to delete
          branch: ${{ github.event.pull_request.head.ref }}
          # Protect dev branch from deletion
          exclude: dev
